### ISSUE TITLE
Docs are rendered incorrectly in Chromium browers

### ISSUE THREAD

**Issue by Moulick** [asciinema/asciinema.github.io#1]
Might be just me but https://docs.asciinema.org/ is being rendered incorrectly on Chromium based browers (I checked Google chrome and Microsoft Edge) but look fine on Safari.

It seems that something is breaking with the Fira Sans font. I can see that `fira.css` is fetched successfully.

Chrome:
<img width="1438" alt="image" src="https://github.com/asciinema/asciinema/assets/15780903/a9e88f75-df73-4f76-aa11-54a346b6c8ed">

Safari:
<img width="1425" alt="image" src="https://github.com/asciinema/asciinema/assets/15780903/32937f69-3c27-475f-9cee-0886f695dcc4">

**Comment by ku1ik** [comment]
Does it look the same in Chrome's Incognito window?

I tested in latest Chrome on macOS and Linux and it looks fine for me.

**Comment by Moulick** [comment]
Same problem in in-cognito. But I just uninstalled the `Fira Sans` font installed on my laptop (from homebrew) and that seems to have fixed it. So maybe somehow the font on the operating system is given higher preference?

**Comment by ku1ik** [comment]
Yes, if there's a font with the same name as defined in fira.css on your system then it's used automatically. It's the `local` directive as seen here: https://github.com/asciinema/asciinema.github.io/blob/main/docs/stylesheets/fira.css#L70

It should have worked just fine without a need for uninstalling... this is weird :thinking: 

I'll try to reproduce this with the homebrew installed font on my system.

**Comment by Moulick** [comment]
I see. Wouldn't it make sense to rather load the font you are shipping vs preferring the system font?

Also, reinstalling the font on my machine seems to have fixed the issue. ¯\\\_(ツ)_/¯

**Comment by ku1ik** [comment]
It makes more sense to use your local copy of the font than to download it from the server, no? :)

I'm glad you figured it out.

**Comment by Moulick** [comment]
From a website designer's perspective, wouldn't you want the website to look consistent across all users irrespective of the locally installed font? Also, the font a website provides could have been patched/updated to add extra symbols like with powerline glyphs which would be missing from a local copy etc.

Thanks for investigating :)

**Comment by ku1ik** [comment]
Well I do know that the one I use here is not patched, so if you have a local font with the same name it should look no different than the copy of it you would (wastefully) download. And even if it looked slightly different I wouldn't mind at all :)
